management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080
  tomcat:
    threads:
      max: 1000

dubbo:
  # 配置服务信息
  application:
    name: order-service
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
  # 配置注册中心
  registry:
    address: nacos://172.16.4.171:8848
  #设置订阅的服务
  cloud:
    subscribed-services: freight-service,goods-fororder-service,other-forOther-service
  # 设置协议-协议由提供方指定消费方被动接受
  protocol:
    name: dubbo
    port: -1
    # 设置超时时间
  consumer:
    timeout: 4000
    check: false


spring:
  main:
    # 解决Bean重复定义问题
    allow-bean-definition-overriding: true
  application:
    name: order
  profiles:
    active: dev
  servlet:
    multipart:
      #是否使用http上传
      enabled: true
      #最大请求文件的大小
      max-request-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.4.171:8848

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialization-mode: never
    schema: classpath:order-schema.sql
    data: classpath:order-data.sql
    druid:
      #初始化时建立物理连接的个数
      initial-size: 3
      #最小连接池数量
      min-idle: 3
      #最大连接池数量
      max-active: 100
      #获取连接时最大等待时间
      max-wait: 60000
      filter:
        stat:
          #是否开启慢sql查询监控
          log-slow-sql: true
          #慢SQL执行时间
          slow-sql-millis: 100
      validation-query: select 1
    sql-script-encoding: UTF-8

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    #连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    # 连接超时时间（毫秒）
    timeout: 5000

mybatis:
  #po对象的包
  type-aliases-package: cn.edu.xmu.order.model
  #mapper.xml所在的位置
  mapper-locations: classpath*:cn.edu.xmu.order.mapper/*.xml
  #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
  configuration:
    #输出产生的SQL
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 配置rocketmq
rocketmq:
  # 指定namesrv地址
  name-server: 172.16.4.195:9876
  producer:
    #生产者group名称
    group: order_producer_group
    #一次发送多少数量消息
    max-message-size: 4096
    #发送消息超时时间,默认3000
    send-message-timeout: 3000
    #发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 2


orderservice:
  #是否对数据库中的未初始化的数据初始化
  initialization: true
  #分布式锁失效时间（秒）
  lockerExpireTime: 30
  #dav信息配置
  dav:
    username: oomall
    password: admin
    baseUrl: http://127.0.0.1:8888/webdav/
  #topic配置信息
  order-pay-topic:
    # 固定的延时等级 "1s 5s 10s 30s 1m 2m 3m 4m 5m 6m 7m 8m 9m 10m 20m 30m 1h 2h"
    delay-level: 16
    #超时时间（秒）
    timeout: 1800
  order-insert-topic:
    timeout: 10
#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql





